version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: password-vault-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: password_vault
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - password-vault-network

  api:
    build: .
    container_name: password-vault-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/password_vault?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      API_PORT: 3000
    depends_on:
      - mongodb
    networks:
      - password-vault-network

volumes:
  mongodb_data:

networks:
  password-vault-network:
    driver: bridge
